apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: batch-job-every-fifteen-minutes
spec:
  # this will invoke cronjob every fifteenth minute every day/month/year
  schedule: "0,15,30,45 * * * *"
  # if this job won't start in 15 seconds, it will be cancelled
  startingDeadlineSeconds: 15
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: preriodic-batch-job
        spec:
          restartPolicy: OnFailure
          containers:
            - name: main
              image: luksa/batch-job
