apiVersion: apps/v1
# ReplicaSet is an enhanced version of ReplicaController.
# Use this rather than ReplicaController.
kind: ReplicaSet
metadata:
  name: kubia
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kubia
    # ReplicaSet can match expressions
    matchExpressions:
      # for example, this will match all the pods that has
      # label key of "app" and its value "kubia"
      - key: app
        operator: In
        values:
          - kubia
      # # this will ignore any pods that have "dev" values for "state" label
      # - key: state
      #   operator: NotIn
      #   values:
      #     - dev
  template:
    metadata:
      labels:
        app: kubia
    spec:
      containers:
        - name: kubia
          image: mrgravity817/kubia
