apiVersion: v1
kind: Pod
metadata:
  name: kubia-liveness
spec:
  containers:
    - name: kubia
      image: luksa/kubia-unhealthy
      # we can check the liveness of the pod from [host]:8080/
      livenessProbe:
        httpGet:
          path: /
          port: 8080
        initialDelaySeconds: 15
