apiVersion: batch/v1
kind: Job
metadata:
  name: multi-seq-batch-job
spec:
  # this will complete 5 pods in 5 rounds = 1 + 1 + 1 + 1 + 1 (sequential)
  completions: 5
  template:
    metadata:
      labels:
        app: batch-job
    spec:
      restartPolicy: OnFailure
      containers:
        - name: main
          image: luksa/batch-job
