apiVersion: v1
kind: Pod
metadata:
  name: fortune-https
spec:
  containers:
    - image: mrgravity817/fortune:env
      name: html-generator
      env:
        - name: INTERVAL
          valueFrom:
            configMapKeyRef:
              name: fortune-config
              key: sleep-interval
      volumeMounts:
        - name: html
          mountPath: /var/htdocs
    - image: nginx:alpine
      name: web-server
      volumeMounts:
        - name: html
          mountPath: /usr/share/nginx/html
          readOnly: true
        - name: config
          mountPath: /etc/nginx/conf.d
          readOnly: true
        - name: certs
          mountPath: /etc/nginx/certs
          readOnly: true
      ports:
        - containerPort: 80
        - containerPort: 443 # for https
  volumes:
    - name: html
      emptyDir: {}
    - name: config
      configMap:
        name: fortune-config
        items: # items props will specify which entry we want to use
          - key: my-nginx-config.conf
            path: gzip.conf
    - name: certs # define volume named "certs"
      secret:
        secretName: fortune-https # which comes from secret named "fortune-https"
