apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubia
spec:
  replicas: 3
  # when app is not ready until 10seconds, this will not be updated
  minReadySeconds: 10
  selector:
    matchLabels:
      app: kubia
  template:
    metadata:
      labels:
        app: kubia
    spec:
      containers:
        - name: nodejs
          image: luksa/kubia:v3
          # Readiness probe will check every 1 second
          readinessProbe:
            periodSeconds: 1
            httpGet:
              path: /
              port: 8080
  strategy:
    # 3~4 pods are tolerated when rolling update
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
