apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pvc
spec:
  # this will find the storage class name we want to connect
  # if we set the name of non-existing storage class name,
  # provisioning will fail.
  storageClassName: fast
  resources:
    requests:
      storage: 100Mi
  accessModes:
    - ReadWriteOnce
