apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pvc
spec:
  resources:
    # requesting 1GB of storage
    requests:
      # PersistentVolume's capacity should be large enough to
      # accommodate this claim.
      storage: 1Gi
  # For a single client, you can support read and write
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
