apiVersion: v1
kind: Service
metadata:
  name: kubia-public
spec:
  selector:
    app: kubia
  ports:
    - port: 80
      targetPort: 8080 # this will publicly connect to port where statefulSet is using
